import React from 'react';

import {View, Text, SectionList, StyleSheet} from 'react-native';

const items = [
  { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }, { title: 'Title1', data: ['item1', 'item2'] }, 
         { title: 'Title2', data: ['item3', 'item4'] }, 
         { title: 'Title3', data: ['item5', 'item6'] }
]

export default class BalanceScreen extends React.Component {
    
  _render = {
    item: ({ item, index, section }) => <Text key={index}>{item}</Text>,
    head_item:({ section: { title } }) => <Text style={{ fontWeight: 'bold' }}>{title}</Text>

  }

  render() {
     return (
      <SectionList
        sections={items}  
        renderItem={this._render.item} 
        renderSectionHeader={this._render.head_item}  />);
    }
}

const styles = StyleSheet.create({

});
